services:
  postgres:
    image: postgres:15
    container_name: dataflowhub_postgres
    environment:
      POSTGRES_DB: dataflowhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dataflowhub_network

  airflow-init:
    image: apache/airflow:2.7.3
    container_name: dataflowhub_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
    user: "50000:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW_UID: "50000"
      AIRFLOW_GID: "0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
      - ./etl:/opt/airflow/etl
      - ./app:/opt/airflow/app
      - ./data:/opt/airflow/data
      - ./processed:/opt/airflow/processed
    depends_on:
      - postgres
    networks:
      - dataflowhub_network

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: dataflowhub_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    user: "50000:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/biking_data
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW_UID: "50000"
      AIRFLOW_GID: "0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
      - ./etl:/opt/airflow/etl
      - ./app:/opt/airflow/app
      - ./data:/opt/airflow/data
      - ./processed:/opt/airflow/processed
    depends_on:
      - airflow-init
    networks:
      - dataflowhub_network

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: dataflowhub_airflow_scheduler
    command: scheduler
    user: "50000:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/biking_data
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW_UID: "50000"
      AIRFLOW_GID: "0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
      - ./etl:/opt/airflow/etl
      - ./app:/opt/airflow/app
      - ./data:/opt/airflow/data
      - ./processed:/opt/airflow/processed
    depends_on:
      - airflow-init
    networks:
      - dataflowhub_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dataflowhub_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/biking_data
      AIRFLOW_URL: http://airflow-webserver:8080
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin
    depends_on:
      - postgres
      - airflow-webserver
    networks:
      - dataflowhub_network
    volumes:
      - ./app:/app
      - ./etl:/etl

volumes:
  postgres_data:

networks:
  dataflowhub_network:
    driver: bridge
